In [2]:
lista2 =[4]*5
lista2

[4, 4, 4, 4, 4]

In [4]:
lista2.append(3)
lista2

[4, 4, 4, 4, 4, 1, 3]

In [9]:
listak=[5,7,9]
listay=[2,3,4]
listak.extend(listay)
listak

[5, 7, 9, 2, 3, 4]

In [11]:
#cancellare elementi della lista
anno =[2015,2016,2018,2020,2023]
del anno [-1]
anno

[2015, 2016, 2018, 2020]

In [12]:
#start e stop. Start incluso, stop escluso (si ferma prima. es. 1-50 farà realmente 1-49)
del anno [0:2]
anno

[2018, 2020]

In [13]:
#remove elimina elementi specifici con ricerca, non per indice. 
anno.remove(2018)
anno

[2020]

In [15]:
anno =[2015,2016,2018,2020,2023]
del anno [0]
anno

[2016, 2018, 2020, 2023]

In [17]:
del anno [-1]
anno

[2016, 2018, 2020]

In [19]:
anno[2]==anno[-1]

True

In [21]:
primi=[11,13,17,19,23,29,31]

In [26]:
for pippo in primi:
    print(pippo)

11
13
17
19
23
29
31


In [27]:
for pippo in primi[0:-3]:
    print(pippo)

11
13
17
19


In [35]:
lista_numerica =list(range(400,300,-2))
(lista_numerica.sort())
lista_numerica

[302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,
 352,
 354,
 356,
 358,
 360,
 362,
 364,
 366,
 368,
 370,
 372,
 374,
 376,
 378,
 380,
 382,
 384,
 386,
 388,
 390,
 392,
 394,
 396,
 398,
 400]

In [36]:
lista2=list(range(0,11,1))
lista2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [2]:
listanumeri= list(range(0,11))
print (listanumeri)

listaquadrati= list() 
for n in (listanumeri):
    listaquadrati.append(n**2)
print(listaquadrati)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [4]:
cubi=[ n**3 for n in (listanumeri)]
print(cubi)

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]


In [5]:
import numpy as np
country = np.array(['USA','UK','Japan'])
country

array(['USA', 'UK', 'Japan'], dtype='<U5')

In [8]:
x = np.array ([[2,3,4,0]])
x.shape

(1, 4)

In [21]:
y = np.array ([[2,3,4,0],[2,1,6,5],['a','b','c','d'],['e','f','g','h']])
print(y.shape)
y

(4, 4)


array([['2', '3', '4', '0'],
       ['2', '1', '6', '5'],
       ['a', 'b', 'c', 'd'],
       ['e', 'f', 'g', 'h']], dtype='<U11')

In [22]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.arange(2,10,dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [26]:
np.linspace(1,4,4)

array([1., 2., 3., 4.])

In [30]:
x=np.array([3,6,9,12])
x= x/3
x

array([1., 2., 3., 4.])

In [41]:
eta = int(input('Inserisci la tua età : '))
if eta < 0:
    print ('come fai ad avere meno di zero anni?')
else:
    if eta >=18:
        print ('sei maggiorenne')
    else:
            print ('non puoi entrare')

sei maggiorenne


In [51]:
eta = int(input('Inserisci la tua età : '))
if eta < 0:
    print ('come fai ad avere meno di zero anni?')
else: 
    patente = str(input('Hai la patente? '))
    if eta >=18 and patente==True:
        print ('daje!')
    else:
        print ('devi prendere la patente prima')

devi prendere la patente prima


In [57]:
eta = int(input('Inserisci la tua età : '))
if eta < 0:
    print ('come fai ad avere meno di zero anni?')
elif eta < 18:
    print ('sei un bimbo, cresci e ripassa')
else: 
    patente = str(input('Hai la patente? '))
    if eta >=18 and patente==True:
        print ('daje!')
    else:
        print ('devi prendere la patente prima')
   
        

devi prendere la patente prima


In [65]:
eta = int(input('Inserisci la tua età : '))
if eta < 0:
    print ('come fai ad avere meno di zero anni?')

else: 
    patente = bool(input('Hai la patente? '))
    if eta >=18 and patente==True:
        print ('daje!')
    elif eta >=18 and patente==False:
        print ('devi prendere la patente prima')
    else : 
        print ('sei un bimbo, cresci e ripassa')

daje!


In [80]:
while True:
    numero = int(input('inserisci un numero '))
    print ('il numero inserito è ', numero)
    if numero >=100:
        print('ok, hai inserito il numero ',numero, 'maggiore di 100, adesso inserisci una lettera :')
        break
vocali = ['a','e','i','o','u']
lettera=input()
while lettera not in vocali:
    print('Inserisci una vocale')
    break

il numero inserito è  5
il numero inserito è  1
il numero inserito è  101
ok, hai inserito il numero  101 maggiore di 100, adesso inserisci una lettera :
Inserisci una vocale


In [1]:
vocali = ['a','e','i','o','u']
while True:
    lettera=input('inserisci una lettera: ')
    if lettera in vocali:
        print('bravo ')
        break

bravo 


In [3]:
def print_tre_volte():
    print('Ciao')
    print('il mio nome è')
    print('Davide')

print_tre_volte()

Ciao
il mio nome è
Davide


In [10]:
def somma_tra_due_numeri(primo_numero,secondo_numero):
    print('questa funzione somma 2 numeri ')
    risultato = primo_numero + secondo_numero
    print('il risultato è ',str(risultato))

somma_tra_due_numeri(int(input()),int(input()))

questa funzione somma 2 numeri 
il risultato è  9


In [2]:

a= int(input())
b= int(input())

def somma_tra_due_numeri(primo_numero:int,secondo_numero:int=6):
    '''questa funzione somma 2 numeri'''
    print('questa funzione somma 2 numeri ')
    risultato = primo_numero + secondo_numero
    print('il risultato è ',str(risultato*2))
    return risultato*2

somma_tra_due_numeri(a)

if somma_tra_due_numeri(a) == 12:
    print ('la somma è corretta')
else:
    print ('errore')

questa funzione somma 2 numeri 
il risultato è  18
questa funzione somma 2 numeri 
il risultato è  18
errore


In [10]:
#RETTANGOLO
def calcoli_rettangolo(base:float,altezza:float):
    '''calcolo perimetro:(return[0]) 
       calcolo area rettangolo:(return[1])'''
    area_rett = base * altezza
    perimetro_rett = (base*2) + (altezza*2)
    return area_rett,perimetro_rett
    

base_rettangolo= float(input('inserisci la base del rettangolo'))
altezza_rettangolo=float(input('inserisci altezza del rettangolo'))

calcoli=calcoli_rettangolo(base_rettangolo,altezza_rettangolo)

print('Area = ',calcoli[0])
print('Perimetro = ',calcoli[1])




Area =  25.0
Perimetro =  20.0


In [19]:
def calcoli_rettangolo(base:float,altezza:float):
    '''calcolo perimetro e area rettangolo'''
    area_rett = base * altezza
    perimetro_rett = (base*2) + (altezza*2)
    return area_rett,perimetro_rett

base_rettangolo= float(input('inserisci la base del rettangolo'))
altezza_rettangolo=float(input('inserisci altezza del rettangolo'))
if base_rettangolo>0 and altezza_rettangolo>0:
    calcolo_area,calcolo_perimetro=calcoli_rettangolo(base_rettangolo,altezza_rettangolo)
    print('Area = ', calcolo_area)
    print('Perimetro = ',calcolo_perimetro)
else:
    print('Devi inserire valori maggiori di 0')

Area =  16.0
Perimetro =  16.0


In [2]:
import numpy as np

def calcoli_cerchio(raggio:float):
    '''calcolo perimetro e area cerchio'''
    area_cerchio = np.pi * raggio**2
    perimetro_cerchio = 2*np.pi*raggio
    return area_cerchio,perimetro_cerchio

raggio= float(input('inserisci il raggio del cerchio'))

calcolo_area_cerchio,calcolo_perimetro_cerchio=calcoli_cerchio(raggio)

print('Area = ', round(calcolo_area_cerchio,2))
print('Perimetro = ',calcolo_perimetro_cerchio)

Area =  14957.12
Perimetro =  433.53978619539146


In [ ]:
from formule import calcoli_cerchio,calcoli_rettangolo

raggio= float(input('inserisci il raggio del cerchio'))

In [2]:
class Persona:
    def __init__(self,a,b): #attributi __init__(self, ) + sintassi
        self.nome = a
        self.eta = b
arturo = Persona ('Arturo',2)
print(arturo)
print (arturo.nome) 

arturo.eta

Arturo


2

In [16]:
class Persona:
    def __init__(self,a,b): #attributi __init__(self, ) è sintassi
        self.nome = a
        self.eta = b
    def double (self,x): #metodo
        return x*2
    def quadratoanni(self): #metodo
        return self.eta**2
    
arturo=Persona('Arturo',2)

dd=arturo.double(int(input()))
bb=arturo.quadratoanni()

print(dd)
bb


4


4

In [1]:
(lambda x:x+1)(4)

5

In [6]:
x= input()
y=input()
(lambda x,y : int(x)+int(y))(x,y)

10

In [14]:
(lambda *args: sorted(args))(1,4,5,3,2) #*args quando gli imput sono indefiniti

[1, 2, 3, 4, 5]